-- Create table for tracking post views
CREATE TABLE IF NOT EXISTS public.post_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL, -- References blog_posts(id) ideally, but keeping loose for MVP if needed
    user_id UUID NOT NULL, -- References auth.users or profiles
    seen_at TIMESTAMPTZ DEFAULT NOW(),

    -- Prevent duplicate views per user per post (optional, or allow multiple views)
    CONSTRAINT unique_user_post_view UNIQUE (post_id, user_id)
);

-- RLS Policies
ALTER TABLE public.post_views ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to insert their own view
CREATE POLICY "Users can insert their own view" ON public.post_views
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Allow everyone (authenticated) to read views (for count)
CREATE POLICY "Authenticated users can view counts" ON public.post_views
    FOR SELECT
    USING (auth.role() = 'authenticated');

-- Function to get view count and names (simplified for RPC if needed)
-- For now, we'll query directly from Flutter using select(count)
